### ISSUE TITLE
Add Administrator permission

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#12]
On the user edit/create screen there needs to be a checkbox to determine if the user is an administrator.  This administrator selection then needs to be persisted for the user.  This permission will be used to authorize user access to administrative functionality.

**Comment by andreburto** [comment]
Working on this now.

**Comment by anthonycrumley** [comment]
Andy is working on this.

**Comment by andreburto** [comment]
The checkbox on the UI works. I can add/remove admin status to/from John Doe as Jane Doe.  Authentication checks are lacking, but I will work on those tomorrow night.
