### ISSUE TITLE
We need a Back button on most pages, instead of having to use the browser back button

### ISSUE THREAD

**Issue by joymac** [edbirmingham/network#123]
Go to the List of Events e.g. and click on an event to view it. We need a way to select a way to go "Back".  i.e. Back Button. Right now, I have to clic
![1-7-2016 11-42-05 amback_button](https://cloud.githubusercontent.com/assets/1828399/12177877/17c401de-b534-11e5-9e74-ab680b6e97f0.png)
k the browser back button.

**Comment by anthonycrumley** [comment]
@ShadowTuner This should be a link to the relevant list page.  This is needed on the edit, create and view pages for each list page, i.e. action, location, member, participant, event and user.

**Comment by rthbound** [comment]
@anthonycrumley to play devil's advocate... if it's just a link to the relevant list/index page, wouldn't "back" be a misnomer when the edit page is accessed from a show page?

**Comment by anthonycrumley** [comment]
@rthbound Good point.  Thanks for the advocacy.  :smile: 

The view page should have a link to the list page.  The create page should have a link to the list page.  The edit page should have a link to the list page and the view page.  They should be more like cookie crumbs than a back button.

**Comment by rthbound** [comment]
Is this still in progress @ShadowTuner ?

If not, I may know someone who's up for tackling this issue...

**Comment by anthonycrumley** [comment]
@rthbound Several new issues have been added to the Ready list in waffle.io.  Please let me know if I can be of assistance.

**Comment by ShadowTuner** [comment]
@rthbound I am still working on this.  I believe I may have a process that will make it work that isn't overly complicated.  I have to make sure I can get it to format out in a way that is user-friendly and aesthetically pleasing.
