### ISSUE TITLE
Filling in new member information is cumbersome. We don't show the errors on the page in a user friendly fashion.

### ISSUE THREAD

**Issue by joymac** [edbirmingham/network#129]
When adding a New Member, I add in information to the fields, I click submit but then I have to scroll back to the top to see the error. At least I think there is an error, since there is nothing on the screen that tells me near the submit button that there is an error. What I believe would be better, would be if we informed the user of the required fields as they are filling them out. Then if one is missed and I were to click the submit button. I would see the error at the top but also at the bottom. Along with an asterisk and the field bordered letting me know what the problem is. 
![1-7-2016 1-32-08 pmmember_error](https://cloud.githubusercontent.com/assets/1828399/12180713/e188b65e-b543-11e5-97bf-98906a9238b4.png)

**Comment by acsellers** [comment]
I'm working on this
