### ISSUE TITLE
Creating a new user, an existing users user name and password is retained. 

### ISSUE THREAD

**Issue by joymac** [edbirmingham/network#133]
I was creating a new user and noticed that when I pulled up the new user screen, an existing users username and password was retained there. See screens. 
![1-8-2016 9-13-57 amexist_user](https://cloud.githubusercontent.com/assets/1828399/12201311/38fb773c-b5e9-11e5-9565-5f356e4f1ead.png)
![1-8-2016 9-13-32 amnew _user](https://cloud.githubusercontent.com/assets/1828399/12201312/38ff4344-b5e9-11e5-8c4f-4c14d3bc57f2.png)

**Comment by atcrawford** [comment]
I'm not sure how to mark this issue as "In Progress". I've added a pull request (#137) which references this issue.
