### ISSUE TITLE
Edit T-Shirt Receipt Quickly from Member List

### ISSUE THREAD

**Issue by saabdoli** [edbirmingham/network#138]
We want to be able to mark off whether a member has received a T-Shirt from the Member List View

Currently, to show that a Member has received a T-Shirt, we must find the member in the Member List, select the Member, view the Member summary page, and click the Edit button.

Instead, we need to be able to update this attribute from the List Page

**Comment by anthonycrumley** [comment]
@marshallpollard @saabdoli This has been released to Heroku.
