### ISSUE TITLE
Using the Forgot Password link takes me to a page to enter the username but renders a 500 internal error

### ISSUE THREAD

**Issue by joymac** [edbirmingham/network#139]
From the signin page, I click the Forgot my Password link. I am then taken to a page to enter my username. Once I do this and click Submit I get a 500 internal error. I don't receive any type of notification telling me what should happen or what has happened. The page remains and the field is blank. Again, there is not a Back button here to take me back to the sign in page. Note: I have the Sign In at the top right, but the user should be gently pointed to the sign in page without having to go to extra lengths or steps to get to it. 
![1-14-2016 11-16-27 amforgot_password](https://cloud.githubusercontent.com/assets/1828399/12331806/dc9c88f6-bab0-11e5-979d-ce8337816013.png)

**Comment by rthbound** [comment]
@joymac this is just a (hopefully) helpful tip. You may already know this, I've just heard this project is helping to get lots of new devs ramped up and I think it might be of help. :)

In that network tab, if you click on the failed request you should be able to find a "preview". That can contain more information pointing to the source of the problem you've encountered. In development modes the preview will often contain an exception and message and will sometimes contain a backtrace pointing to the file and line number that failed. In production modes, less information is surfaced for security reasons.

**Comment by acsellers** [comment]
It looks like it's trying to mail out a forgot password email, but the development environment doesn't have a mail server setup.
