### ISSUE TITLE
Fix "Recruiter needed" error

### ISSUE THREAD

**Issue by marshallpollard** [edbirmingham/network#144]

**Comment by marshallpollard** [comment]
At Connector Table Meeting (1.12.16), when attempting to add Connector A to the participant list, it was required to add "recruiter". All Connectors are members...may have something to do with a required field for membership registration

**Comment by anthonycrumley** [comment]
@marshallpollard This fix has been released to Heroku.  What I did was a quick fix to remove the required fields for saving members.

**Comment by marshallpollard** [comment]
Great!

On Tue, Jan 19, 2016 at 11:14 AM, Anthony Crumley <notifications@github.com>
wrote:

> @marshallpollard <https://github.com/marshallpollard> This fix has been
> released to Heroku. What I did was a quick fix to remove the required
> fields for saving members.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edbirmingham/network/issues/144#issuecomment-172922303>
> .
>



-- 


<http://edbirmingham.org/>

Marshall Pollard

Director of Community Partnerships

Birmingham Education Foundation

call.      205-503-3595

give.     donate.edbirmingham.org

follow.  Twitter <https://twitter.com/iamedbirmingham> ||  Instagram
<https://instagram.com/iamedbirmingham/> || Facebook
<https://www.facebook.com/iamedbirmingham> || YouTube
<https://www.youtube.com/user/weareedbirmingham>

join.     become a Network Member
<https://docs.google.com/forms/d/1qDdBFiqiNHoIxq2Qp1VQByzUtDS_Tc3aQqG1bu53WOg/viewform>
