### ISSUE TITLE
Network Member Registration

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#18]
During a network night, some participants will become network members.  A volunteer will enter people into the system as members.  Members are participants with extra information and a membership indicator.

See the story of release [0.1.0](https://github.com/edbirmingham/network/wiki/Story-of-0.1.0-Release) for context.

**Comment by anthonycrumley** [comment]
Current google form:

<img width="724" alt="ed_network_member_registration_form" src="https://cloud.githubusercontent.com/assets/2340/9391957/7aa2a7aa-473f-11e5-920d-e0324e4c5bfc.png">

<img width="724" alt="ed_network_member_registration_form" src="https://cloud.githubusercontent.com/assets/2340/9392008/b4d04586-473f-11e5-86f5-67e2ac039b2b.png">

<img width="717" alt="ed_network_member_registration_form" src="https://cloud.githubusercontent.com/assets/2340/9392030/cdaebb14-473f-11e5-9749-6d747ff7249a.png">

**Comment by marshallpollard** [comment]
We need to be able to differentiate between where these Network Members are coming from i.e.:
-Staff recruitment (each staff person being able to document that they recruited the member)
-Network Night
-Career Development Conference 
-Bridging the Gap
-Connector Recruitment (each Connector being able to document that they recruited the member) 
-Educator Roundtable
-Parent Pathways
-Gear Up 
-Miscellaneous Event (ability to input event name, i.e. UAB Faculty/Staff presentation) 

That way, we can track where our Network Members are coming from to hit program goals and hold individuals (staff/Connectors) accountable
