### ISSUE TITLE
HIGH PRIORITY: Filtering/Export Membership

### ISSUE THREAD

**Issue by marshallpollard** [edbirmingham/network#187]
We need to be able to:

1) Export members into an excel/CSV file so that we can add members emails/phones to our communication distribution 

2) Identify members who joined and need to receive a membership card

3) Easily search members by name, location, affiliation, etc.

**Comment by marshallpollard** [comment]
This is a high priority because right now, we are unable to update our communication lists (mail chimp and EZ Texting) and therefore, newly joined NMs have ZERO evidence of their membership. They are not being kept in the loop, receiving their card, etc.

**Comment by anthonycrumley** [comment]
Google docs is an option for where to create the spreadsheet from the database.
