### ISSUE TITLE
Startup script doesn't startup if grunt is already running

### ISSUE THREAD

**Issue by andreburto** [edbirmingham/network#192]
The startup script needs to be extended to check to see if the Network app is running not just look for grunt in the process list. Suggest using curl or wget to see if the page is served on port 80.

**Comment by andreburto** [comment]
@anthonycrumley Would you have any objections to me adding a /status or /check route to the app that would return a simple "success" message? With that I could extend the startup script so it could check to see if the app was running and not stop if another grunt application was in the process list. It would also allow external health checks of the Network.

**Comment by anthonycrumley** [comment]
@andreburto That sounds like a great idea!!!  Please do.
