### ISSUE TITLE
Add script to load fake data for development.

### ISSUE THREAD

**Issue by mwleeds** [edbirmingham/network#195]
We should make an automated way (perhaps in the "grunt initdb" command) to add fake data to the MongoDB instance that we can use during development.

**Comment by andreburto** [comment]
@mwleeds @anthonycrumley Where is current test data located? Engineyard? If someone could dump that I'll write a script to load it. If it doesn't exist I can begin generating it.

**Comment by andreburto** [comment]
Talked with @anthonycrumley and I'll start generating data in my local copy of Network.
