### ISSUE TITLE
Sign In Participants

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#21]
As a volunteer, I want to sign in new participants so that they are known in the network and can be interacted with.

See the story of release [0.1.0](https://github.com/edbirmingham/network/wiki/Story-of-0.1.0-Release) for context.

### Acceptance Criterion 1:

**Given** that the participant is attending their first Ed event
And they were not previously entered into Network by a connector
**When** they arrive at an Ed event
**Then** ensure that they were not previously entered into Network
And record their name
And record their phone number
And record their email address
And record their identity (student, parent, educator, resident or community partner
And record their affiliation (i.e. UAB, Carver High School, Literacy Council)
And submit the participants information
And Network is ready for the next participant

### Acceptance Criterion 2:

**Given** that the participant was previously entered by a connector
**When** they arrive at an Ed event
**Then** find them in the Network
And mark them as attended
And inform them that they are in Network
And inform them that next time they can just go through the record attendance line ( #35 )
And Network is ready for the next participant

### Acceptance Criterion 3:

**Given** that the participant is attending their first Ed event
And they were not previously entered into Network by a connector
And they are able to enter themselves into the Network
**When** they arrive at an Ed event
And a volunteer determines they are able to enter themselves into the Network
**Then** the volunteer ensures that they were not previously entered into Network
And the volunteer gives a tablet to the participant
And they enter their name
And they enter their phone number
And they enter their email address
And they enter their identity (student, parent, educator, resident or community partner
And they enter their affiliation (i.e. UAB, Carver High School, Literacy Council)
And they submit the information
And Network is ready for the next participant
And the participant gives the tablet back to the volunteer

### Notes
* The comments related to photographs are not part of this issue.  New issues were created to implement that separately.  See issues #29 and #30.
* See the google form screenshot below as an example.
* The "Number of students with you?" question is really part of recording attendance which is in issue #35  and should not be implemented in this issue.

**Comment by anthonycrumley** [comment]
Current Google Form:
<img width="722" alt="ed_network_gathering_guest_sign_in" src="https://cloud.githubusercontent.com/assets/2340/9393020/4f6fe038-4745-11e5-9dbe-2dd900c88b4b.png">
<img width="717" alt="ed_network_gathering_guest_sign_in" src="https://cloud.githubusercontent.com/assets/2340/9393034/6ce23d78-4745-11e5-842c-6cfd35127be4.png">

**Comment by andreburto** [comment]
Would the cycle for this be: sign in screen, "Thank you for signing in" screen, automatic reload, and back to sign in screen?

**Comment by anthonycrumley** [comment]
@andreburto Yes, that would be the flow.  Since this is an angular app the entire page would not be reloaded, just the sign in screen.

**Comment by andreburto** [comment]
Would taking a picture of participants be possible at sign in? I can see why people might object, but it might also speed up/increase accuracy of note taking by volunteers if they could match a face rather than a name.

Benefits:
- Makes it easier to identify people in the interface. (Or does it? They have name tags.)
- Puts a picture with matches and nodes automatically for the Hot List

Concerns:
- Might be off-putting to some people.
- Privacy issues.
- Camera API for the browser their tablet uses.

**Comment by anthonycrumley** [comment]
@marshallpollard What do you think about @andreburto's suggestion about taking pictures at signin?

**Comment by marshallpollard** [comment]
Speak more to it...I don't think I'm clear in what this process would look like. Here's my understanding/concerns:

Understanding:
-Participant comes to sign in table
-Person signs in using interface
-Takes picture/picture is logged in their sign in file
-Volunteers/Connectors are able to use picture to remember what participant looks like during Network Night and when following up with participant 

Concerns (if I'm understanding process correctly):
-I think this will slow sign in down significantly--explaining the picture taking process, participants asking why their picture is taken, etc. 
-Unless privacy was checked off during sign in, this becomes a huge concern.

**Comment by marshallpollard** [comment]
This does make me think that we need to add a privacy question on the sign in....something to this effect:

"We take pictures to capture the story unfolding during Network Night. Do you give us permission to take photos of you/around you?"

**Comment by andreburto** [comment]
I think I misunderstood the sign in process, because I was picturing:

- Volunteers at a table with tablets
- Participants pick up a tablet and fill out the form themselves
- Participant returns the tablet for the next person

In hindsight I can see where that would bottleneck the sign in process since you would have to deal with the Participants varying levels of familiarity with tablets, apps, etc.

**Comment by anthonycrumley** [comment]
@marshallpollard @andreburto I think the photographs are a good idea but that we need to add them at a latter time.  Therefore, I am creating separate issues to add photographs to the sign in process and to the member registration process.

See issues #29 #30.
