### ISSUE TITLE
Show event attendance by member

### ISSUE THREAD

**Issue by awmitchell1** [edbirmingham/network#233]
Currently I can look at an event and see who all was there. I would like to search by participant, and see all of the events they have attended.

**Comment by acsellers** [comment]
working on this

**Comment by anthonycrumley** [comment]
A table should be added to the bottom of the member page showing all their event participations.  The table should include the columns Event#name, Event#program, Location#name, Event#date, Participation#created_at and a destroy column.

This issue is dependent on #268.

**Comment by jzw** [comment]
I'm working on this.
