### ISSUE TITLE
Add role based permissions

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#247]
The rails upgrade has not included permissions yet.

There needs to be an admin permission that can get to all the current functionality.  If the user is not an admin then they can't do anything right now.

* By default the users are created without a role.
* If a user does not have the admin role then none of the links should appear other than the Network home page link and the links under the username dropdown, which are edit profile and logout.
* #263 must be completed before there will be a place to assign roles.

**Comment by tmiller** [comment]
Look into use the following gems:

* cancancan (replaced cancan)
* pundit
