### ISSUE TITLE
Convert User CRUD to Rails

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#263]
The user signup, profile update, login, logout, forgot password and such were all created by the Devise generator.  There is a Users link in the top navigation that should allow administrators to manage users.  Issue #247 is dependent on this issue to be able to manage user roles.

**Comment by tmiller** [comment]
@anthonycrumley I can't find where the user signup is accessible. Should a user be able to sign up themselves or do we need a users#new action where an administrator creates an account for them?

**Comment by tmiller** [comment]
I just realized I was looking at the MeanJS version when I couldn't find the signup link. However my question still stands will people be able to sign up by themselves?

**Comment by anthonycrumley** [comment]
@tmiller The default devise generator allows them to sign themselves up.  I am ok with this be we need to make sure they can't do anything right now until they have the administrator role/permission added to them.

**Comment by anthonycrumley** [comment]
@tmiller I think the devise signup stuff is in an engine.  There is a way to move it into the project if it needs some customization but I am not sure that it will need that.

**Comment by tmiller** [comment]
Yea, we shouldn't need it for a little while.
