### ISSUE TITLE
Export events to a csv

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#277]
The events on the event list page should be exportable to a csv file with all the event attributes included.  The file should have a header with the column names matching the attribute names.

**Comment by andreburto** [comment]
@anthonycrumley Which would be the best way to initiate the download: an option in the dropdown menu or a button next to the add event button?

**Comment by andreburto** [comment]
@anthonycrumley @saabdoli Sorry if this is an obvious question, but for location and program do you want anything besides the names in the column? Right now it's just the ID, I have to link the tables, but should I pull anything else (address) while I'm there? Or is the ID number the right thing to have in the CSV?

https://github.com/andreburto/network/blob/andy_list_dump/app/models/network_event.rb

**Comment by anthonycrumley** [comment]
@andreburto For the program, just the name, for the location, the name and address.

**Comment by andreburto** [comment]
@anthonycrumley Please check the "andy_list_dump" branch. I've got the CSV exporting, but I noticed an oddity when I ran the test: all that comes back is the header. When I run the update in my branch I get a CSV download with the entries. The test only sends back the header, even though the network_event.yml file has two entries. I used a puts in the test and as far as I can tell everything is coming through the HTTP call as it should, the response.body shows up with the header as a string, but there's nothing more. Am I doing something wrong?

**Comment by anthonycrumley** [comment]
@andreburto That is a tricky one.  

First, the controller with the csv comment is the NetworkActionsController rather than the NetworkEventsController so maybe the wrong controller is being considered.

https://github.com/edbirmingham/network/compare/master...andreburto:andy_list_dump#diff-a57bbf52c504ebff0c541418ef33fd88R6

Second, the NetworkEventsController has filters on the index method.  The default filter is to return events from the next week.

https://github.com/andreburto/network/blob/fed6b932ede18638af950e454d29f0489c195b12/app/controllers/network_events_controller.rb#L5-L17

The network events in the test fixtures currently have a fixed date that is now in the past.

https://github.com/andreburto/network/blob/fed6b932ede18638af950e454d29f0489c195b12/test/fixtures/network_events.yml#L3-L15

Try replacing the static scheduled at dates of `2016-06-20 01:59:56` to something like the following and the events will begin exporting because their scheduled at dates will be in the next week:
```
one:
  name: MyString
  program: one
  location: one
  scheduled_at: <%= 2.days.from_now %>
  user: one
```

I hope this helps.  😄

**Comment by andreburto** [comment]
@anthonycrumley Running the tests took longer than a second, which was failing because the times were different. I modified the Network Event controller so when it had no ranges and the format was CSV it dumped everything. The tests pass and I can open the data in Excel. Created a pull request #364

**Comment by hollivc** [comment]
Program, Event name, date, start and end times, school, cohort, grade, school contact, site contact
