### ISSUE TITLE
Associate members with organizations

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#288]
Add an has_man :through relationship from Member to Organization.  Add the ability to associate zero to many organizations to a member on the member edit page.  Add relationships between members and organizations to the seeds file.

**Comment by saabdoli** [comment]
Do you think the term "membership" or "memberships" is too confusing to use as the name for the associations?

**Comment by anthonycrumley** [comment]
In this context the Member is a member of Ed.  The relationship between a Member and an Organization should be called something other than a membership because that would be confusing.  We probably should have called the Member a Person but we can consider that later.  How does affiliation sound?

```
class Affiliation
  belongs_to :member
  belongs_to :organization
end

class Member
  has_many :affiliations
  has_many :organizations, through: :affiliations
end

class Organization
  has_many :affiliations
  has_many :members, through: :affiliations
end
```
