### ISSUE TITLE
Add talent management

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#293]
A basic rails scaffold should be used to create talent CRUD screens. The model will just have a name for now. Seeds should be added with some examples like "Arts", "Math", "Technology. A has_many :through association should be used to associate members with talents.

**Comment by tsmith1024** [comment]
Would like to claim this issue, if there are no problems with that.

**Comment by saabdoli** [comment]
That should be fine. I'll go ahead and assign the issue to you. Thanks for your hard work!!
