### ISSUE TITLE
Add photographs to the member signup page

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#30]
See discussion in #21 concerning photographs.

# Understanding:
* Participant comes to member sign up table
* Volunteer registers new member using interface
* Takes picture/picture is logged in their membership record
* Volunteers/Connectors are able to use picture to remember what member looks like during Network Night and when following up with member

# Benefits
* Makes it easier to identify people in the interface. (Or does it? They have name tags.)
* Puts a picture with matches and nodes automatically for the Hot List

# Concerns
* Might be off-putting to some people.
* Privacy issues.
* Camera API for the browser their tablet uses.
* This could slow membership registration down some--explaining the picture taking process, members asking why their picture is taken, etc. 
* Unless privacy was checked off during registration, this becomes a huge concern. This does make me think that we need to add a privacy question on the registration....something to this effect: "We take pictures to capture the story unfolding during Network Night. Do you give us permission to take photos of you/around you?"

**Comment by andreburto** [comment]
The camera API issue isn't the issue I assumed it was thanks to HTML5. As far as I know most mobile browsers handle HTML5 pretty well. Time permitting I'll tinker and see if I can get a prototype working on my phone this weekend. Here's a couple of relevant links if anyone's curious:

http://davidwalsh.name/browser-camera

http://www.html5rocks.com/en/tutorials/getusermedia/intro/
