### ISSUE TITLE
Add location administration

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#31]
Add functionality for listing, creating, editing and deleting network event locations. Authorization to perform this functionality needs to be controlled by the administrator permission #12.

See the story of release [0.1.0](https://github.com/edbirmingham/network/wiki/Story-of-0.1.0-Release) for context.

**Comment by jzw** [comment]
@anthonycrumley for purposes of this story, do locations need anything more than a `name` attribute?

Note the crud-module generator also includes a `created` timestamp and a `user` foreign key referencing the user who creates the record.

**Comment by anthonycrumley** [comment]
@jzw The name would be sufficient.  We may add other things later.
