### ISSUE TITLE
Assign category to Actions

### ISSUE THREAD

**Issue by awmitchell1** [edbirmingham/network#335]
All actions will receive one of 4 categories for Ed staff internal tracking of completion. Staff will develop ranking system and needs ability to add category to each action. Similar to assigning owner. 

Quick Wins - Ed staff will track
Major Projects - push out to Priority Councils
Fill Ins - push out to Junior Board, volunteers
Hard Slogs - avoid

**Comment by anthonycrumley** [comment]
This will be implemented in #577.
