### ISSUE TITLE
Search for members by identity

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#448]
The member list page needs search filter for identity.  The member download link needs to respect this filter.  See the event list page for examples of how to implement the filters.

**Comment by Mcosta02** [comment]
Hi anthonycrumley. Can I work on this issue? Many Thanks

**Comment by Mcosta02** [comment]
Hi @anthonycrumley. Could I work on this issue? Many Thanks

**Comment by anthonycrumley** [comment]
@Mcosta02 Absolutely.  Looking forward to a pull request.

**Comment by Mcosta02** [comment]
Hi Anthony. I've submmited the pull request. Please let me know any trouble.

Cheers
