### ISSUE TITLE
Update gems to fix Rails 5 warnings

### ISSUE THREAD

**Issue by tmiller** [edbirmingham/network#472]

**Comment by jamescook** [comment]
I'm just going to go ahead and upgrade to 5.1 which was released right around the time network was updated to 5.0. And fix the deprecations along the way.

**Comment by tmiller** [comment]
I tried to take care of most of the deprecations when I upgraded to 5.0.

**Comment by jamescook** [comment]
There were some new deprecations from bumping other gems, such as Devise. And some carry-over from an unrelated PR that was merged after your work that re-introduced some deprecations :)
