### ISSUE TITLE
Autocomplete not working for members

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#495]
On the network event edit page, the autocomplete for member selection is not working.

**Comment by anthonycrumley** [comment]
![Ed_Network.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e07f446d77391200c87f2b/125516c66e82c728ace21e0d46cd90a50d8797be80fbb401e81fe086264c22703d46f96925d0e678e8447a58095d4ca9415c5b40fcf9882aafe76925984019af80330b2b9b645bf9fa9015ad02b82a8a4b8cbebc8c4ac0ec3c2ce68f9d02.png)

**Comment by jamescook** [comment]
I think this is possibly a regression from the 5.1 update. The Member.search method is receiving a ActionController::Parameters object that doesn't respond to 'split'. Calling 'to_h' on the params fixes the problem. I'll work on that and add a test.
