### ISSUE TITLE
Send email to people associated with an event

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#496]
In order to be able to communicate with the people involved in events as volunteers or contacts, we need to be able to select an event and send an email to the site contacts, school contacts and volunteers.

**Comment by jamescook** [comment]
@anthonycrumley Rough outline of the backend: https://gist.github.com/jamescook/9cc054943f31fe9df5165c3084244caa
Thoughts?

**Comment by jamescook** [comment]
Progress: 
![Screen Shot 2017-06-28 at 9.04.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59382ebc2147660020f94da2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456fb6b7191a371f1122f4f5d575ecc3c4a4356bcbbd671f3e57862804e0ee8846d5822973447aeba871fbb05be208b4e84bfeddf19d2f42f67b6d5db1063474f4dcbed5727a39841c95cff43e64d54ac133661ef752431.png)
