### ISSUE TITLE
Improve checkin speed

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#539]
When checking in members to an event after the fact, it would be more efficient to be able to select multiple members with a checkbox and then checkin all the selected members at once by clicking one button at the bottom of the page labeled something like "Checkin all selected members".  This way the user does not have to wait on the page to update and refresh for each member checked in.

**Comment by shresthamit07** [comment]
I will look into it.

**Comment by shresthamit07** [comment]
Pull Request: https://github.com/edbirmingham/network/pull/558/files?diff=split&w=1
