### ISSUE TITLE
Add members in groups

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#546]
When entering new members into the network they will often be related by school, cohort and graduating class.  Therefore, a group member adding page should be created to facilitate entering groups of members.

When first navigating to the group member add page, all the fields will be blank.  There should be a "Create Member and Stop" button that returns to the members listing after creating the member.  There should be a "Create Member and Another" button that creates a member and then comes back to the group add page with the common fields populated from the last member creation and the Specific fields cleared for the next new member.

Common Fields (maintained for each new member):
* Graduating class
* Cohorts
* School
* Identity
* Organizations

Specific Fields (cleared for each new member):
* First Name
* Last Name
* Email
* Phone
* Address
* City
* State
* Zip Code
* Shirt Size

**Comment by vishwasja** [comment]
PR : https://github.com/edbirmingham/network/pull/560
