### ISSUE TITLE
Average Student Attendance

### ISSUE THREAD

**Issue by KCDada** [edbirmingham/network#611]
Overview: This year we are tracking average student attendance with a goal that each event has 80% attendance of those who were invited to the event.

Issue: Currently, the report tracks the average student attendees as an average of the total number of students. We would like an average of the attendance percentages for each event. For example, if Event 1 has 70% attendance and Event 2 has 80% attendance the total average attendance is 75%.

**Comment by anthonycrumley** [comment]
@KCDada The attendance percentage has been added to the Events By Program report.

https://network.edbirmingham.org/reports/events_by_program
