### ISSUE TITLE
Numbered Columns

### ISSUE THREAD

**Issue by meyemtunagur** [edbirmingham/network#658]
An added first column where you can see how many individuals, events, programs etc. you are looking at. For example, if I needed to see how many members are in the 12th grade Wenonah Career Academy cohort, it would be very helpful if the table numbered how many individuals matched that search.

**Comment by anthonycrumley** [comment]
@meyemtunagur Does the count on the Member search results provide the information you were looking for here?

<img width="1252" alt="searchcount" src="https://user-images.githubusercontent.com/2340/48812191-d2f23a00-ecf6-11e8-95d6-6c554074ae4e.png">
