### ISSUE TITLE
Auto-populating fields

### ISSUE THREAD

**Issue by cecelacey** [edbirmingham/network#659]
As I am updating alumni information I realized all former responses show up as options when entering information. This could be problematic for: phone, email, twitter handle, facebook name, instagram handle, GPA, ACT score.

**Comment by Trevonte** [comment]
Just fixed all autocompletes within the text fields. Should not show any previous information within the forms.

**Comment by anthonycrumley** [comment]
Completed by #683

**Comment by anthonycrumley** [comment]
@cecelacey This problem should be fixed by an update Trevonte' made.
