### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#664]
Setup a Cloud9 development environment and demonstrate it by attaching the following screenshots to this issue.  Make sure each screenshot includes the address bar.

* Members screen.
* Events screen.
* Tasks screen.
* Cohorts admin screen.
* Common tasks admin screen.
* Users admin screen.

**Comment by Trevonte** [comment]
@anthonycrumley Here are the screenshots for each page:
<img width="960" alt="common tasks" src="https://user-images.githubusercontent.com/42625251/46168360-dff62e00-c25d-11e8-9c27-d46b77184e17.png">
<img width="960" alt="events" src="https://user-images.githubusercontent.com/42625251/46168361-dff62e00-c25d-11e8-8f7c-c0e1bda4f3c8.png">
<img width="960" alt="members" src="https://user-images.githubusercontent.com/42625251/46168362-dff62e00-c25d-11e8-96df-cad3b45c9e5e.png">
<img width="960" alt="tasks" src="https://user-images.githubusercontent.com/42625251/46168363-e08ec480-c25d-11e8-9b22-bfbabc3a4b1d.png">
<img width="960" alt="users admin" src="https://user-images.githubusercontent.com/42625251/46168364-e08ec480-c25d-11e8-8ad7-fa152e80c283.png">
<img width="960" alt="cohorts admin" src="https://user-images.githubusercontent.com/42625251/46168365-e08ec480-c25d-11e8-9213-2acc07bfa017.png">

**Comment by anthonycrumley** [comment]
@Trevonte Nice work!!  I really appreciate the address bar being in the screenshots.  👍
