### ISSUE TITLE
Setup learning cloud9 environment

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#665]
Create a new Cloud9 environment for learning Ruby and Rails.  That may be easier than trying to set it up on your computer.

1) Log into AWS and go to the Cloud9 service.
2) Click the orange Create Environment button.
<img width="1235" alt="create_environment" src="https://user-images.githubusercontent.com/2340/44946498-017d0a80-adc3-11e8-86ba-5e3c25748bdb.png">

3) Name the environment and click the next button.
<img width="1161" alt="name_environment" src="https://user-images.githubusercontent.com/2340/44946504-0b9f0900-adc3-11e8-95c8-4269de083cbd.png">

4) On the Configure Settings page, just let all the default values be and click the Next Step button.
5) On the review page, click the Create environment button.  This should start you up a new development environment.

As with the other environment, be sure to close the tab when you are not using it so that I won't get charged extra for it.

The next time you log into AWS Cloud9 you will see both environments and can click the Open IDE button in which ever environment you want to use.  Your AWS Cloud9 environments page will then look something like the following except with your specific environment names.

<img width="1221" alt="your_environments" src="https://user-images.githubusercontent.com/2340/44946506-19548e80-adc3-11e8-8f9e-3806ec78ca00.png">

Once you have the environment setup, complete the getting started Rails guide (https://guides.rubyonrails.org/v4.2/getting_started.html).  If you run into problems or have any questions along the way, reach out to me in gitter.  When you have completed the getting started guide then we will have a video meeting for you to demonstrate the application you create and to discuss the things you learned.

**Comment by Trevonte** [comment]
The environment was successfully set up, and I'm now working on the "Ruby on Rails Guide".

<img width="960" alt="new environment" src="https://user-images.githubusercontent.com/42625251/46425199-aa8b8d80-c700-11e8-8f61-55b25cf4c606.png">
<img width="960" alt="new environment" src="https://user-images.githubusercontent.com/42625251/46425277-d575e180-c700-11e8-9121-1d7e939d8271.png">

**Comment by Trevonte** [comment]
@anthonycrumley Finished the Ruby Rails Guide Setup and successfully created a blog with working Articles, Comments, and password authentication. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/42625251/48016909-81409180-e0f2-11e8-88e8-40c23ec39c2d.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/42625251/48016957-a0d7ba00-e0f2-11e8-84dd-45580f34758e.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/42625251/48017008-bf3db580-e0f2-11e8-8b53-fc3c16ba4d7e.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/42625251/48017387-c9ac7f00-e0f3-11e8-91eb-436ecc9bffc3.png">

**Comment by anthonycrumley** [comment]
@Trevonte Great!!  I will find an issue that you are ready to complete and assign it to you.
