### ISSUE TITLE
Can we add to types of communication log

### ISSUE THREAD

**Issue by cecelacey** [edbirmingham/network#671]
**Is your feature request related to a problem? Please describe.**
When going to add communication with a member in the database only options are email, thank you, and donation request.

**Describe the solution you'd like**
Could we add "text" and "call" as options?

**Describe alternatives you've considered**
I looked to see if I could add a mode of communication like adding tasks or adding identities, etc. But i did not see a way, this could be a possibility too.

**Additional context**
<img width="1226" alt="screen shot 2018-10-02 at 3 21 52 pm" src="https://user-images.githubusercontent.com/38887844/46374857-61cbca00-c657-11e8-96be-d4bdf840d20a.png">

**Comment by anthonycrumley** [comment]
@cecelacey Text and call options have been added and deployed.  They should be in the list now.
