### ISSUE TITLE
Filter buttons are not showing correctly

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#677]
**Describe the bug**
The "Filter events" button on the Events page works properly.  The "Filter members" button on the Members page and the "Filter tasks" button on the Tasks page show the text but not the button.

**Expected behavior**
All the filter buttons should look like the "Filter Events" button.

**Screenshots**
<img width="1265" alt="filterevents" src="https://user-images.githubusercontent.com/2340/48170845-f2cd3b00-e2be-11e8-9a17-4e7ffa12bda9.png">
<img width="1271" alt="filtermembers" src="https://user-images.githubusercontent.com/2340/48170895-31fb8c00-e2bf-11e8-9eb1-69cb12e414ae.png">
<img width="1269" alt="filtertasks" src="https://user-images.githubusercontent.com/2340/48170896-31fb8c00-e2bf-11e8-931a-8150cf497715.png">

**Comment by Trevonte** [comment]
@anthonycrumley Fixed the issue of the filter button within the "Members" and "Tasks" page not showing properly. I changed the "btn btn-secondary" to "btn btn-primary". Currently no issues!
<img width="482" alt="image2" src="https://user-images.githubusercontent.com/42625251/48298131-64eb7e80-e47d-11e8-951d-34b13dbfd317.png">

**Comment by anthonycrumley** [comment]
Fixed by #682
