### ISSUE TITLE
Action event filter needs more information

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#684]
**Describe the bug**
The event filter on the actions page does not show enough information to be able to differentiate similar events.

**To Reproduce**
1. Go to the Actions page.
2. Click on 'Filter by Events'.
3. Notice that only the event name is shown.  Many events have the same name but different dates and locations.

**Expected behavior**
The event filter on the Actions page should show the event name, date and location in the same format as is shown on the Tasks page event filter.

**Screenshots**
Actions page without enough event information.
<img width="1255" alt="screen shot 2018-11-27 at 6 28 57 pm" src="https://user-images.githubusercontent.com/2340/49120475-6f29bd00-f272-11e8-8b90-b39c80735a4d.png">

Tasks page that has enough information.
<img width="1263" alt="screen shot 2018-11-27 at 6 29 17 pm" src="https://user-images.githubusercontent.com/2340/49120491-7bae1580-f272-11e8-8f3e-60cef4516c6d.png">

**Comment by Trevonte** [comment]
Just fixed the issue, pull request has been sent!

**Comment by anthonycrumley** [comment]
Fixed and Merged.
