### ISSUE TITLE
Participant signin instructions for volunteers

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#87]
In order to signin participants better and with less confusion, as a volunteer I want an instruction sheet that helps me understand how to sign participants into the Network Database.

Notes:
* Some volunteers where not sure if they needed to clear the Find participant box before entering the information for the participant in the other fields.

**Comment by saabdoli** [comment]
https://docs.google.com/document/d/1uugBQNPHtymQ7Gxv-ev5kCHwgiIwHJv-31GtMZakfoo/edit?usp=sharing

Here is a link for the latest version of this with screenshots.
