### ISSUE TITLE
Add filtering to members list.

### ISSUE THREAD

**Issue by anthonycrumley** [edbirmingham/network#89]
In order to more easily find a participant from the large number of them, as an administrator I want to be able to filter them by name.

**Comment by marshallpollard** [comment]
Filter by school, identify, affiliation, name, etc.
Filter by "Network Door" (Raise Up Initiatives" Educate Local, etc.) 
Filter by person who inputted them???? (Marshall Pollard user, Ed Volunteer User, etc.)
